const elements = [
    { atomicNumber: 1, symbol: 'H', name: 'Hydrogen', description: 'The lightest and most abundant element in the universe.', category: 'nonmetal' },
    { atomicNumber: 2, symbol: 'He', name: 'Helium', description: 'A noble gas used in balloons and as a cooling medium in cryogenics.', category: 'noble gas' },
    { atomicNumber: 3, symbol: 'Li', name: 'Lithium', description: 'A soft, silvery metal used in rechargeable batteries.', category: 'alkali metal' },
    { atomicNumber: 4, symbol: 'Be', name: 'Beryllium', description: 'A rare, steel-gray metal used in aerospace components.', category: 'alkaline earth metal' },
    { atomicNumber: 5, symbol: 'B', name: 'Boron', description: 'A metalloid used in glass and ceramics.', category: 'metalloid' },
    { atomicNumber: 6, symbol: 'C', name: 'Carbon', description: 'The basis of all life, found in all organic molecules.', category: 'nonmetal' },
    { atomicNumber: 7, symbol: 'N', name: 'Nitrogen', description: 'A major component of the Earth’s atmosphere, used in fertilizers.', category: 'nonmetal' },
    { atomicNumber: 8, symbol: 'O', name: 'Oxygen', description: 'Essential for respiration and water formation.', category: 'nonmetal' },
    { atomicNumber: 9, symbol: 'F', name: 'Fluorine', description: 'A highly reactive nonmetal used in toothpaste and Teflon.', category: 'nonmetal' },
    { atomicNumber: 10, symbol: 'Ne', name: 'Neon', description: 'A noble gas used in neon signs and high-voltage indicators.', category: 'noble gas' },
    { atomicNumber: 11, symbol: 'Na', name: 'Sodium', description: 'A soft, reactive metal used in salt and street lights.', category: 'alkali metal' },
    { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', description: 'A metal used in alloys and fireworks.', category: 'alkaline earth metal' },
    { atomicNumber: 13, symbol: 'Al', name: 'Aluminum', description: 'A lightweight metal used in packaging and construction.', category: 'post-transition metal' },
    { atomicNumber: 14, symbol: 'Si', name: 'Silicon', description: 'A metalloid used in computer chips and solar panels.', category: 'metalloid' },
    { atomicNumber: 15, symbol: 'P', name: 'Phosphorus', description: 'Essential for DNA and ATP, used in fertilizers.', category: 'nonmetal' },
    { atomicNumber: 16, symbol: 'S', name: 'Sulfur', description: 'Used in sulfuric acid and matches.', category: 'nonmetal' },
    { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', description: 'A disinfectant used in bleach and swimming pools.', category: 'nonmetal' },
    { atomicNumber: 18, symbol: 'Ar', name: 'Argon', description: 'A noble gas used in inert gas welding and lighting.', category: 'noble gas' },
    { atomicNumber: 19, symbol: 'K', name: 'Potassium', description: 'A reactive metal used in fertilizers and salt substitutes.', category: 'alkali metal' },
    { atomicNumber: 20, symbol: 'Ca', name: 'Calcium', description: 'Essential for bones and teeth, used in cement and lime.', category: 'alkaline earth metal' },
    { atomicNumber: 21, symbol: 'Sc', name: 'Scandium', description: 'A rare metal used in aluminum alloys and sports equipment.', category: 'transition metal' },
    { atomicNumber: 22, symbol: 'Ti', name: 'Titanium', description: 'A strong, corrosion-resistant metal used in aerospace and medical implants.', category: 'transition metal' },
    { atomicNumber: 23, symbol: 'V', name: 'Vanadium', description: 'A metal used in steel alloys and as a catalyst.', category: 'transition metal' },
    { atomicNumber: 24, symbol: 'Cr', name: 'Chromium', description: 'Used in stainless steel and chrome plating.', category: 'transition metal' },
    { atomicNumber: 25, symbol: 'Mn', name: 'Manganese', description: 'Used in steel production and as a catalyst in batteries.', category: 'transition metal' },
    { atomicNumber: 26, symbol: 'Fe', name: 'Iron', description: 'A key component of steel and vital for blood oxygen transport.', category: 'transition metal' },
    { atomicNumber: 27, symbol: 'Co', name: 'Cobalt', description: 'Used in batteries, magnets, and blue pigments.', category: 'transition metal' },
    { atomicNumber: 28, symbol: 'Ni', name: 'Nickel', description: 'Used in stainless steel and coins.', category: 'transition metal' },
    { atomicNumber: 29, symbol: 'Cu', name: 'Copper', description: 'A conductive metal used in wiring and plumbing.', category: 'transition metal' },
    { atomicNumber: 30, symbol: 'Zn', name: 'Zinc', description: 'Used in galvanizing steel and as an essential trace element.', category: 'transition metal' },
    { atomicNumber: 31, symbol: 'Ga', name: 'Gallium', description: 'Used in electronics and solar panels.', category: 'post-transition metal' },
    { atomicNumber: 32, symbol: 'Ge', name: 'Germanium', description: 'Used in semiconductors and fiber optics.', category: 'metalloid' },
    { atomicNumber: 33, symbol: 'As', name: 'Arsenic', description: 'A toxic metalloid used in pesticides and semiconductors.', category: 'metalloid' },
    { atomicNumber: 34, symbol: 'Se', name: 'Selenium', description: 'Used in electronics and as a nutritional supplement.', category: 'nonmetal' },
    { atomicNumber: 35, symbol: 'Br', name: 'Bromine', description: 'A halogen used in flame retardants and disinfectants.', category: 'nonmetal' },
    { atomicNumber: 36, symbol: 'Kr', name: 'Krypton', description: 'A noble gas used in high-efficiency lighting.', category: 'noble gas' },
    { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium', description: 'A highly reactive metal used in research and fireworks.', category: 'alkali metal' },
    { atomicNumber: 38, symbol: 'Sr', name: 'Strontium', description: 'Used in fireworks and in the production of ferrite magnets.', category: 'alkaline earth metal' },
    { atomicNumber: 39, symbol: 'Y', name: 'Yttrium', description: 'Used in LEDs, superconductors, and cancer treatment.', category: 'transition metal' },
    { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium', description: 'Used in nuclear reactors and ceramic materials.', category: 'transition metal' },
    { atomicNumber: 41, symbol: 'Nb', name: 'Niobium', description: 'Used in superconductors and steel alloys.', category: 'transition metal' },
    { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum', description: 'Used in steel alloys and catalysts.', category: 'transition metal' },
    { atomicNumber: 43, symbol: 'Tc', name: 'Technetium', description: 'A radioactive element used in medical imaging.', category: 'transition metal' },
    { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium', description: 'Used in electrical contacts and as a catalyst.', category: 'transition metal' },
    { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium', description: 'Used in catalytic converters and jewelry.', category: 'transition metal' },
    { atomicNumber: 46, symbol: 'Pd', name: 'Palladium', description: 'Used in catalytic converters and hydrogen storage.', category: 'transition metal' },
    { atomicNumber: 47, symbol: 'Ag', name: 'Silver', description: 'Used in jewelry, electronics, and as an antimicrobial agent.', category: 'transition metal' },
    { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium', description: 'Used in batteries and pigments, but is toxic.', category: 'transition metal' },
    { atomicNumber: 49, symbol: 'In', name: 'Indium', description: 'Used in electronics and as a component of touchscreens.', category: 'post-transition metal' },
    { atomicNumber: 50, symbol: 'Sn', name: 'Tin', description: 'Used in coatings and alloys like bronze.', category: 'post-transition metal' },
    { atomicNumber: 51, symbol: 'Sb', name: 'Antimony', description: 'Used in flame retardants and semiconductors.', category: 'metalloid' },
    { atomicNumber: 52, symbol: 'Te', name: 'Tellurium', description: 'Used in alloys and as a semiconductor material.', category: 'metalloid' },
    { atomicNumber: 53, symbol: 'I', name: 'Iodine', description: 'Essential for thyroid function and used in antiseptics.', category: 'nonmetal' },
    { atomicNumber: 54, symbol: 'Xe', name: 'Xenon', description: 'A noble gas used in high-intensity lamps and anesthesia.', category: 'noble gas' },
    { atomicNumber: 55, symbol: 'Cs', name: 'Cesium', description: 'Used in atomic clocks and in oil drilling.', category: 'alkali metal' },
    { atomicNumber: 56, symbol: 'Ba', name: 'Barium', description: 'Used in medical imaging and fireworks.', category: 'alkaline earth metal' },
    { atomicNumber: 57, symbol: 'La', name: 'Lanthanum', description: 'Used in camera lenses and catalysts.', category: 'lanthanoid' },
    { atomicNumber: 58, symbol: 'Ce', name: 'Cerium', description: 'Used in catalytic converters and as a polishing agent.', category: 'lanthanoid' },
    { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium', description: 'Used in magnets and as a colorant in glass.', category: 'lanthanoid' },
    { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium', description: 'Used in strong magnets and lasers.', category: 'lanthanoid' },
    { atomicNumber: 61, symbol: 'Pm', name: 'Promethium', description: 'A rare, radioactive element used in luminous paint.', category: 'lanthanoid' },
    { atomicNumber: 62, symbol: 'Sm', name: 'Samarium', description: 'Used in magnets and as a neutron absorber in nuclear reactors.', category: 'lanthanoid' },
    { atomicNumber: 63, symbol: 'Eu', name: 'Europium', description: 'Used in phosphorescent materials and color television.', category: 'lanthanoid' },
    { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium', description: 'Used in MRI contrast agents and nuclear reactors.', category: 'lanthanoid' },
    { atomicNumber: 65, symbol: 'Tb', name: 'Terbium', description: 'Used in green phosphors and as a dopant in fiber optics.', category: 'lanthanoid' },
    { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium', description: 'Used in magnets and laser materials.', category: 'lanthanoid' },
    { atomicNumber: 67, symbol: 'Ho', name: 'Holmium', description: 'Used in lasers and magnetic alloys.', category: 'lanthanoid' },
    { atomicNumber: 68, symbol: 'Er', name: 'Erbium', description: 'Used in lasers and as a colorant in glass and ceramics.', category: 'lanthanoid' },
    { atomicNumber: 69, symbol: 'Tm', name: 'Thulium', description: 'Used in lasers and as a component in some alloys.', category: 'lanthanoid' },
    { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium', description: 'Used in lasers and as a dopant in fiber optics.', category: 'lanthanoid' },
    { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium', description: 'Used in catalysts and in high-temperature superconductors.', category: 'lanthanoid' },
    { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium', description: 'Used in nuclear reactors and in alloys.', category: 'transition metal' },
    { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum', description: 'Used in electronics and surgical implants.', category: 'transition metal' },
    { atomicNumber: 74, symbol: 'W', name: 'Tungsten', description: 'Used in lightbulb filaments and cutting tools.', category: 'transition metal' },
    { atomicNumber: 75, symbol: 'Re', name: 'Rhenium', description: 'Used in jet engines and as a catalyst.', category: 'transition metal' },
    { atomicNumber: 76, symbol: 'Os', name: 'Osmium', description: 'The densest naturally occurring element, used in electronics.', category: 'transition metal' },
    { atomicNumber: 77, symbol: 'Ir', name: 'Iridium', description: 'Used in spark plugs and as a corrosion-resistant metal.', category: 'transition metal' },
    { atomicNumber: 78, symbol: 'Pt', name: 'Platinum', description: 'Used in catalytic converters and jewelry.', category: 'transition metal' },
    { atomicNumber: 79, symbol: 'Au', name: 'Gold', description: 'A precious metal used in jewelry and electronics.', category: 'transition metal' },
    { atomicNumber: 80, symbol: 'Hg', name: 'Mercury', description: 'A liquid metal used in thermometers and barometers.', category: 'transition metal' },
    { atomicNumber: 81, symbol: 'Tl', name: 'Thallium', description: 'Used in electronics and as a poison.', category: 'post-transition metal' },
    { atomicNumber: 82, symbol: 'Pb', name: 'Lead', description: 'Used in batteries and radiation shielding, but is toxic.', category: 'post-transition metal' },
    { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth', description: 'Used in cosmetics and as a non-toxic replacement for lead.', category: 'post-transition metal' },
    { atomicNumber: 84, symbol: 'Po', name: 'Polonium', description: 'A highly radioactive element used in antistatic devices.', category: 'post-transition metal' },
    { atomicNumber: 85, symbol: 'At', name: 'Astatine', description: 'A rare, radioactive element with no significant applications.', category: 'metalloid' },
    { atomicNumber: 86, symbol: 'Rn', name: 'Radon', description: 'A radioactive noble gas that can cause lung cancer.', category: 'noble gas' },
    { atomicNumber: 87, symbol: 'Fr', name: 'Francium', description: 'The least stable and rarest alkali metal.', category: 'alkali metal' },
    { atomicNumber: 88, symbol: 'Ra', name: 'Radium', description: 'A highly radioactive element once used in luminescent paint.', category: 'alkaline earth metal' },
    { atomicNumber: 89, symbol: 'Ac', name: 'Actinium', description: 'A radioactive element used in cancer treatment.', category: 'actinoid' },
    { atomicNumber: 90, symbol: 'Th', name: 'Thorium', description: 'A radioactive metal used in nuclear reactors.', category: 'actinoid' },
    { atomicNumber: 91, symbol: 'Pa', name: 'Protactinium', description: 'A rare, radioactive element used in nuclear research.', category: 'actinoid' },
    { atomicNumber: 92, symbol: 'U', name: 'Uranium', description: 'Used as fuel in nuclear reactors and in nuclear weapons.', category: 'actinoid' },
    { atomicNumber: 93, symbol: 'Np', name: 'Neptunium', description: 'A radioactive element used in nuclear research.', category: 'actinoid' },
    { atomicNumber: 94, symbol: 'Pu', name: 'Plutonium', description: 'Used in nuclear weapons and reactors.', category: 'actinoid' },
    { atomicNumber: 95, symbol: 'Am', name: 'Americium', description: 'Used in smoke detectors and as a neutron source.', category: 'actinoid' },
    { atomicNumber: 96, symbol: 'Cm', name: 'Curium', description: 'Used in scientific research and as a neutron source.', category: 'actinoid' },
    { atomicNumber: 97, symbol: 'Bk', name: 'Berkelium', description: 'Used in scientific research and as a neutron source.', category: 'actinoid' },
    { atomicNumber: 98, symbol: 'Cf', name: 'Californium', description: 'Used in neutron radiography and as a neutron source.', category: 'actinoid' },
    { atomicNumber: 99, symbol: 'Es', name: 'Einsteinium', description: 'Used in scientific research.', category: 'actinoid' },
    { atomicNumber: 100, symbol: 'Fm', name: 'Fermium', description: 'Used in scientific research.', category: 'actinoid' },
    { atomicNumber: 101, symbol: 'Md', name: 'Mendelevium', description: 'Used in scientific research.', category: 'actinoid' },
    { atomicNumber: 102, symbol: 'No', name: 'Nobelium', description: 'Used in scientific research.', category: 'actinoid' },
    { atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium', description: 'Used in scientific research.', category: 'actinoid' },
    { atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium', description: 'Used in scientific research.', category: 'transition metal' },
    { atomicNumber: 105, symbol: 'Db', name: 'Dubnium', description: 'Used in scientific research.', category: 'transition metal' },
    { atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium', description: 'Used in scientific research.', category: 'transition metal' },
    { atomicNumber: 107, symbol: 'Bh', name: 'Bohrium', description: 'Used in scientific research.', category: 'transition metal' },
    { atomicNumber: 108, symbol: 'Hs', name: 'Hassium', description: 'Used in scientific research.', category: 'transition metal' },
    { atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium', description: 'Used in scientific research.', category: 'transition metal' },
    { atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium', description: 'Used in scientific research.', category: 'transition metal' },
    { atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium', description: 'Used in scientific research.', category: 'transition metal' },
    { atomicNumber: 112, symbol: 'Cn', name: 'Copernicium', description: 'Used in scientific research.', category: 'post-transition metal' },
    { atomicNumber: 113, symbol: 'Nh', name: 'Nihonium', description: 'Used in scientific research.', category: 'post-transition metal' },
    { atomicNumber: 114, symbol: 'Fl', name: 'Flerovium', description: 'Used in scientific research.', category: 'post-transition metal' },
    { atomicNumber: 115, symbol: 'Mc', name: 'Moscovium', description: 'Used in scientific research.', category: 'post-transition metal' },
    { atomicNumber: 116, symbol: 'Lv', name: 'Livermorium', description: 'Used in scientific research.', category: 'post-transition metal' },
    { atomicNumber: 117, symbol: 'Ts', name: 'Tennessine', description: 'Used in scientific research.', category: 'metalloid' },
    { atomicNumber: 118, symbol: 'Og', name: 'Oganesson', description: 'A synthetic noble gas used in scientific research.', category: 'noble gas' }
];



// Function to update the element box with the clicked element's information
function showElementInfo(element) {
    const elementBox = document.getElementById('element-box');
    elementBox.innerHTML = `
        <h2>${element.name} (${element.symbol})</h2>
        <p><strong>Description:</strong> ${element.description}</p>
        <p><strong>Category:</strong> ${element.category}</p>
    `;
}

// Event listener for the element buttons
document.querySelectorAll('.element').forEach(button => {
    button.addEventListener('click', () => {
        const atomicNumber = parseInt(button.dataset.atomicNumber, 10);
        const element = elements.find(e => e.atomicNumber === atomicNumber);
        if (element) {
            showElementInfo(element);
        }
    });
});