const express = require('express');
const path = require('path');
const app = express();
const port = 3000;

// Serve static files (including images) from the 'public' directory
app.use(express.static('public'));

// Example API endpoint to fetch element data
app.get('/api/elements/:elementName', (req, res) => {
    const elementName = req.params.elementName;
// Array with element data including image URLs
const elements = {
  { atomicNumber: 1, symbol: 'H', name: 'Hydrogen', category: 'nonmetal', description: 'Hydrogen is the lightest and most abundant element in the universe.', image: 'https://example.com/images/hydrogen.png' },
  { atomicNumber: 2, symbol: 'He', name: 'Helium', category: 'noble gas', description: 'Helium is a noble gas used in balloons and as a coolant in cryogenics.', image: 'https://example.com/images/helium.png' },
  { atomicNumber: 3, symbol: 'Li', name: 'Lithium', category: 'alkali metal', description: 'Lithium is used in rechargeable batteries and as a medication for bipolar disorder.', image: 'https://example.com/images/lithium.png' },
  { atomicNumber: 4, symbol: 'Be', name: 'Beryllium', category: 'alkaline earth metal', description: 'Beryllium is used in aerospace materials and as a neutron moderator in nuclear reactors.', image: 'https://example.com/images/beryllium.png' },
  { atomicNumber: 5, symbol: 'B', name: 'Boron', category: 'metalloid', description: 'Boron is used in glass and ceramics, and as a nutrient in plant fertilizers.', image: 'https://example.com/images/boron.png' },
  { atomicNumber: 6, symbol: 'C', name: 'Carbon', category: 'nonmetal', description: 'Carbon is a fundamental building block of life and is used in various materials including diamonds and graphite.', image: 'https://example.com/images/carbon.png' },
  { atomicNumber: 7, symbol: 'N', name: 'Nitrogen', category: 'nonmetal', description: 'Nitrogen makes up about 78% of Earth\'s atmosphere and is used in fertilizers and explosives.', image: 'https://example.com/images/nitrogen.png' },
  { atomicNumber: 8, symbol: 'O', name: 'Oxygen', category: 'nonmetal', description: 'Oxygen is essential for respiration and combustion, and makes up a large part of Earth\'s crust.', image: 'https://example.com/images/oxygen.png' },
  { atomicNumber: 9, symbol: 'F', name: 'Fluorine', category: 'halogen', description: 'Fluorine is used in toothpaste and Teflon, and is highly reactive.', image: 'https://example.com/images/fluorine.png' },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon', category: 'noble gas', description: 'Neon is used in neon signs and high-voltage indicators.', image: 'https://example.com/images/neon.png' },
  { atomicNumber: 11, symbol: 'Na', name: 'Sodium', category: 'alkali metal', description: 'Sodium is essential for nerve function and is used in table salt.', image: 'https://example.com/images/sodium.png' },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', category: 'alkaline earth metal', description: 'Magnesium is used in alloys and as a dietary supplement.', image: 'https://example.com/images/magnesium.png' },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminum', category: 'post-transition metal', description: 'Aluminum is widely used in packaging and construction materials.', image: 'https://example.com/images/aluminum.png' },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon', category: 'metalloid', description: 'Silicon is used in computer chips and glass production.', image: 'https://example.com/images/silicon.png' },
  { atomicNumber: 15, symbol: 'P', name: 'Phosphorus', category: 'nonmetal', description: 'Phosphorus is used in fertilizers and detergents.', image: 'https://example.com/images/phosphorus.png' },
  { atomicNumber: 16, symbol: 'S', name: 'Sulfur', category: 'nonmetal', description: 'Sulfur is used in sulfuric acid and as a fungicide.', image: 'https://example.com/images/sulfur.png' },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', category: 'halogen', description: 'Chlorine is used in disinfectants and bleach.', image: 'https://example.com/images/chlorine.png' },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon', category: 'noble gas', description: 'Argon is used in inert gas welding and as a filling gas in light bulbs.', image: 'https://example.com/images/argon.png' },
  { atomicNumber: 19, symbol: 'K', name: 'Potassium', category: 'alkali metal', description: 'Potassium is essential for cell function and is used in fertilizers.', image: 'https://example.com/images/potassium.png' },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium', category: 'alkaline earth metal', description: 'Calcium is essential for bones and teeth, and is used in cement.', image: 'https://example.com/images/calcium.png' },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium', category: 'transition metal', description: 'Scandium is used in alloys and as a catalyst.', image: 'https://example.com/images/scandium.png' },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium', category: 'transition metal', description: 'Titanium is used in strong, lightweight alloys and aerospace applications.', image: 'https://example.com/images/titanium.png' },
  { atomicNumber: 23, symbol: 'V', name: 'Vanadium', category: 'transition metal', description: 'Vanadium is used in steel alloys and as a catalyst.', image: 'https://example.com/images/vanadium.png' },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium', category: 'transition metal', description: 'Chromium is used in stainless steel and as a chrome plating.', image: 'https://example.com/images/chromium.png' },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese', category: 'transition metal', description: 'Manganese is used in steel production and as a dietary supplement.', image: 'https://example.com/images/manganese.png' },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron', category: 'transition metal', description: 'Iron is used in construction and as a dietary mineral.', image: 'https://example.com/images/iron.png' },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt', category: 'transition metal', description: 'Cobalt is used in batteries and as a catalyst.', image: 'https://example.com/images/cobalt.png' },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel', category: 'transition metal', description: 'Nickel is used in stainless steel and coinage.', image: 'https://example.com/images/nickel.png' },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper', category: 'transition metal', description: 'Copper is used in electrical wiring and plumbing.', image: 'https://example.com/images/copper.png' },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc', category: 'transition metal', description: 'Zinc is used in galvanizing and as an alloying element.', image: 'https://example.com/images/zinc.png' },
  { atomicNumber: 31, symbol: 'Ga', name: 'Gallium', category: 'post-transition metal', description: 'Gallium is used in electronics and as a component in LEDs.', image: 'https://example.com/images/gallium.png' },
  { atomicNumber: 32, symbol: 'Ge', name: 'Germanium', category: 'metalloid', description: 'Germanium is used in semiconductors and fiber optics.', image: 'https://example.com/images/germanium.png' },
  { atomicNumber: 33, symbol: 'As', name: 'Arsenic', category: 'metalloid', description: 'Arsenic is used in pesticides and semiconductors.', image: 'https://example.com/images/arsenic.png' },
  { atomicNumber: 34, symbol: 'Se', name: 'Selenium', category: 'nonmetal', description: 'Selenium is used in electronics and as a dietary supplement.', image: 'https://example.com/images/selenium.png' },
  { atomicNumber: 35, symbol: 'Br', name: 'Bromine', category: 'halogen', description: 'Bromine is used in flame retardants and as a disinfectant.', image: 'https://example.com/images/bromine.png' },
  { atomicNumber: 36, symbol: 'Kr', name: 'Krypton', category: 'noble gas', description: 'Krypton is used in high-performance lighting and lasers.', image: 'https://example.com/images/krypton.png' },
  { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium', category: 'alkali metal', description: 'Rubidium is used in research and atomic clocks.', image: 'https://example.com/images/rubidium.png' },
  { atomicNumber: 38, symbol: 'Sr', name: 'Strontium', category: 'alkaline earth metal', description: 'Strontium is used in fireworks and in making glass for color TV tubes.', image: 'https://example.com/images/strontium.png' },
  { atomicNumber: 39, symbol: 'Y', name: 'Yttrium', category: 'transition metal', description: 'Yttrium is used in superconductors and phosphors.', image: 'https://example.com/images/yttrium.png' },
  { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium', category: 'transition metal', description: 'Zirconium is used in nuclear reactors and as a component in ceramics.', image: 'https://example.com/images/zirconium.png' },
  { atomicNumber: 41, symbol: 'Nb', name: 'Niobium', category: 'transition metal', description: 'Niobium is used in steel alloys and superconductors.', image: 'https://example.com/images/niobium.png' },
  { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum', category: 'transition metal', description: 'Molybdenum is used in steel alloys and electrical contacts.', image: 'https://example.com/images/molybdenum.png' },
  { atomicNumber: 43, symbol: 'Tc', name: 'Technetium', category: 'transition metal', description: 'Technetium is used in medical imaging and as a radioactive tracer.', image: 'https://example.com/images/technetium.png' },
  { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium', category: 'transition metal', description: 'Ruthenium is used in electrical contacts and as a catalyst.', image: 'https://example.com/images/ruthenium.png' },
  { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium', category: 'transition metal', description: 'Rhodium is used in catalytic converters and jewelry.', image: 'https://example.com/images/rhodium.png' },
  { atomicNumber: 46, symbol: 'Pd', name: 'Palladium', category: 'transition metal', description: 'Palladium is used in catalytic converters and as a jewelry metal.', image: 'https://example.com/images/palladium.png' },
  { atomicNumber: 47, symbol: 'Ag', name: 'Silver', category: 'transition metal', description: 'Silver is used in jewelry, coins, and electronics.', image: 'https://example.com/images/silver.png' },
  { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium', category: 'transition metal', description: 'Cadmium is used in batteries and as a pigment.', image: 'https://example.com/images/cadmium.png' },
  { atomicNumber: 49, symbol: 'In', name: 'Indium', category: 'post-transition metal', description: 'Indium is used in electronics and as a component in alloys.', image: 'https://example.com/images/indium.png' },
  { atomicNumber: 50, symbol: 'Sn', name: 'Tin', category: 'post-transition metal', description: 'Tin is used in soldering and as a coating for other metals.', image: 'https://example.com/images/tin.png' },
  { atomicNumber: 51, symbol: 'Sb', name: 'Antimony', category: 'metalloid', description: 'Antimony is used in flame retardants and alloys.', image: 'https://example.com/images/antimony.png' },
  { atomicNumber: 52, symbol: 'Te', name: 'Tellurium', category: 'metalloid', description: 'Tellurium is used in alloys and semiconductors.', image: 'https://example.com/images/tellurium.png' },
  { atomicNumber: 53, symbol: 'I', name: 'Iodine', category: 'halogen', description: 'Iodine is used in disinfectants and as a dietary supplement.', image: 'https://example.com/images/iodine.png' },
  { atomicNumber: 54, symbol: 'Xe', name: 'Xenon', category: 'noble gas', description: 'Xenon is used in high-intensity lamps and anesthesia.', image: 'https://example.com/images/xenon.png' },
  { atomicNumber: 55, symbol: 'Cs', name: 'Cesium', category: 'alkali metal', description: 'Cesium is used in atomic clocks and as a drilling fluid.', image: 'https://example.com/images/cesium.png' },
  { atomicNumber: 56, symbol: 'Ba', name: 'Barium', category: 'alkaline earth metal', description: 'Barium is used in contrast agents for X-rays and in fireworks.', image: 'https://example.com/images/barium.png' },
  { atomicNumber: 57, symbol: 'La', name: 'Lanthanum', category: 'lanthanoid', description: 'Lanthanum is used in catalysts and glass production.', image: 'https://example.com/images/lanthanum.png' },
  { atomicNumber: 58, symbol: 'Ce', name: 'Cerium', category: 'lanthanoid', description: 'Cerium is used in catalysts and polishing powders.', image: 'https://example.com/images/cerium.png' },
  { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium', category: 'lanthanoid', description: 'Praseodymium is used in magnets and glasses.', image: 'https://example.com/images/praseodymium.png' },
  { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium', category: 'lanthanoid', description: 'Neodymium is used in strong magnets and lasers.', image: 'https://example.com/images/neodymium.png' },
  { atomicNumber: 61, symbol: 'Pm', name: 'Promethium', category: 'lanthanoid', description: 'Promethium is used in luminous paints and as a radiation source.', image: 'https://example.com/images/promethium.png' },
  { atomicNumber: 62, symbol: 'Sm', name: 'Samarium', category: 'lanthanoid', description: 'Samarium is used in magnets and cancer treatment.', image: 'https://example.com/images/samarium.png' },
  { atomicNumber: 63, symbol: 'Eu', name: 'Europium', category: 'lanthanoid', description: 'Europium is used in phosphorescent materials and in television screens.', image: 'https://example.com/images/europium.png' },
  { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium', category: 'lanthanoid', description: 'Gadolinium is used in MRI contrast agents and nuclear reactors.', image: 'https://example.com/images/gadolinium.png' },
  { atomicNumber: 65, symbol: 'Tb', name: 'Terbium', category: 'lanthanoid', description: 'Terbium is used in phosphors and solid-state devices.', image: 'https://example.com/images/terbium.png' },
  { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium', category: 'lanthanoid', description: 'Dysprosium is used in high-strength magnets and nuclear reactors.', image: 'https://example.com/images/dysprosium.png' },
  { atomicNumber: 67, symbol: 'Ho', name: 'Holmium', category: 'lanthanoid', description: 'Holmium is used in lasers and nuclear reactors.', image: 'https://example.com/images/holmium.png' },
  { atomicNumber: 68, symbol: 'Er', name: 'Erbium', category: 'lanthanoid', description: 'Erbium is used in fiber optics and lasers.', image: 'https://example.com/images/erbium.png' },
  { atomicNumber: 69, symbol: 'Tm', name: 'Thulium', category: 'lanthanoid', description: 'Thulium is used in lasers and medical imaging.', image: 'https://example.com/images/thulium.png' },
  { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium', category: 'lanthanoid', description: 'Ytterbium is used in lasers and as a dopant in fiber optics.', image: 'https://example.com/images/ytterbium.png' },
  { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium', category: 'lanthanoid', description: 'Lutetium is used in catalysts and cancer treatment.', image: 'https://example.com/images/lutetium.png' },
  { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium', category: 'transition metal', description: 'Hafnium is used in nuclear reactors and high-temperature ceramics.', image: 'https://example.com/images/hafnium.png' },
  { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum', category: 'transition metal', description: 'Tantalum is used in capacitors and surgical instruments.', image: 'https://example.com/images/tantalum.png' },
  { atomicNumber: 74, symbol: 'W', name: 'Tungsten', category: 'transition metal', description: 'Tungsten is used in lightbulb filaments and heavy metal alloys.', image: 'https://example.com/images/tungsten.png' },
  { atomicNumber: 75, symbol: 'Re', name: 'Rhenium', category: 'transition metal', description: 'Rhenium is used in high-temperature superalloys and catalysts.', image: 'https://example.com/images/rhenium.png' },
  { atomicNumber: 76, symbol: 'Os', name: 'Osmium', category: 'transition metal', description: 'Osmium is used in electrical contacts and as a catalyst.', image: 'https://example.com/images/osmium.png' },
  { atomicNumber: 77, symbol: 'Ir', name: 'Iridium', category: 'transition metal', description: 'Iridium is used in spark plugs and as a catalyst.', image: 'https://example.com/images/iridium.png' },
  { atomicNumber: 78, symbol: 'Pt', name: 'Platinum', category: 'transition metal', description: 'Platinum is used in jewelry, catalytic converters, and laboratory equipment.', image: 'https://example.com/images/platinum.png' },
  { atomicNumber: 79, symbol: 'Au', name: 'Gold', category: 'transition metal', description: 'Gold is used in jewelry, electronics, and as a form of currency.', image: 'https://example.com/images/gold.png' },
  { atomicNumber: 80, symbol: 'Hg', name: 'Mercury', category: 'transition metal', description: 'Mercury is used in thermometers and fluorescent lamps.', image: 'https://example.com/images/mercury.png' },
  { atomicNumber: 81, symbol: 'Tl', name: 'Thallium', category: 'post-transition metal', description: 'Thallium is used in electronics and as a component in some optical glasses.', image: 'https://example.com/images/thallium.png' },
  { atomicNumber: 82, symbol: 'Pb', name: 'Lead', category: 'post-transition metal', description: 'Lead is used in batteries and as a radiation shield.', image: 'https://example.com/images/lead.png' },
  { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth', category: 'post-transition metal', description: 'Bismuth is used in cosmetics and as a replacement for lead in some applications.', image: 'https://example.com/images/bismuth.png' },
  { atomicNumber: 84, symbol: 'Po', name: 'Polonium', category: 'post-transition metal', description: 'Polonium is a highly radioactive element used in antistatic devices.', image: 'https://example.com/images/polonium.png' },
  { atomicNumber: 85, symbol: 'At', name: 'Astatine', category: 'halogen', description: 'Astatine is a rare and highly radioactive element.', image: 'https://example.com/images/astatine.png' },
  { atomicNumber: 86, symbol: 'Rn', name: 'Radon', category: 'noble gas', description: 'Radon is a radioactive noble gas found in the decay of uranium and thorium.', image: 'https://example.com/images/radon.png' },
  { atomicNumber: 87, symbol: 'Fr', name: 'Francium', category: 'alkali metal', description: 'Francium is a highly radioactive element with no significant commercial applications.', image: 'https://example.com/images/francium.png' },
  { atomicNumber: 88, symbol: 'Ra', name: 'Radium', category: 'alkaline earth metal', description: 'Radium is used in some medical treatments and was historically used in luminous paints.', image: 'https://example.com/images/radium.png' },
  { atomicNumber: 89, symbol: 'Ac', name: 'Actinium', category: 'actinoid', description: 'Actinium is used in radiation therapy and as a neutron source.', image: 'https://example.com/images/actinium.png' },
  { atomicNumber: 90, symbol: 'Th', name: 'Thorium', category: 'actinoid', description: 'Thorium is used in nuclear reactors and as a component in some high-temperature ceramics.', image: 'https://example.com/images/thorium.png' },
  { atomicNumber: 91, symbol: 'Pa', name: 'Protactinium', category: 'actinoid', description: 'Protactinium is used in scientific research and in some nuclear reactors.', image: 'https://example.com/images/protactinium.png' },
  { atomicNumber: 92, symbol: 'U', name: 'Uranium', category: 'actinoid', description: 'Uranium is used as fuel in nuclear reactors and in nuclear weapons.', image: 'https://example.com/images/uranium.png' },
  { atomicNumber: 93, symbol: 'Np', name: 'Neptunium', category: 'actinoid', description: 'Neptunium is used in some nuclear applications and as a precursor for plutonium.', image: 'https://example.com/images/neptunium.png' },
  { atomicNumber: 94, symbol: 'Pu', name: 'Plutonium', category: 'actinoid', description: 'Plutonium is used in nuclear weapons and as a fuel in some nuclear reactors.', image: 'https://example.com/images/plutonium.png' },
  { atomicNumber: 95, symbol: 'Am', name: 'Americium', category: 'actinoid', description: 'Americium is used in smoke detectors and some medical applications.', image: 'https://example.com/images/americium.png' },
  { atomicNumber: 96, symbol: 'Cm', name: 'Curium', category: 'actinoid', description: 'Curium is used in scientific research and as a source of alpha particles.', image: 'https://example.com/images/curium.png' },
  { atomicNumber: 97, symbol: 'Bk', name: 'Berkelium', category: 'actinoid', description: 'Berkelium is used in scientific research and as a source of neutrons.', image: 'https://example.com/images/berkelium.png' },
  { atomicNumber: 98, symbol: 'Cf', name: 'Californium', category: 'actinoid', description: 'Californium is used in nuclear reactors and as a neutron source.', image: 'https://example.com/images/californium.png' },
  { atomicNumber: 99, symbol: 'Es', name: 'Einsteinium', category: 'actinoid', description: 'Einsteinium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/einsteinium.png' },
  { atomicNumber: 100, symbol: 'Fm', name: 'Fermium', category: 'actinoid', description: 'Fermium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/fermium.png' },
  { atomicNumber: 101, symbol: 'Md', name: 'Mendelevium', category: 'actinoid', description: 'Mendelevium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/mendelevium.png' },
  { atomicNumber: 102, symbol: 'No', name: 'Nobelium', category: 'actinoid', description: 'Nobelium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/nobelium.png' },
  { atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium', category: 'actinoid', description: 'Lawrencium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/lawrencium.png' },
  { atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium', category: 'transition metal', description: 'Rutherfordium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/rutherfordium.png' },
  { atomicNumber: 105, symbol: 'Db', name: 'Dubnium', category: 'transition metal', description: 'Dubnium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/dubnium.png' },
  { atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium', category: 'transition metal', description: 'Seaborgium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/seaborgium.png' },
  { atomicNumber: 107, symbol: 'Bh', name: 'Bohrium', category: 'transition metal', description: 'Bohrium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/bohrium.png' },
  { atomicNumber: 108, symbol: 'Hs', name: 'Hassium', category: 'transition metal', description: 'Hassium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/hassium.png' },
  { atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium', category: 'transition metal', description: 'Meitnerium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/meitnerium.png' },
  { atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium', category: 'transition metal', description: 'Darmstadtium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/darmstadtium.png' },
  { atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium', category: 'transition metal', description: 'Roentgenium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/roentgenium.png' },
  { atomicNumber: 112, symbol: 'Cn', name: 'Copernicium', category: 'transition metal', description: 'Copernicium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/copernicium.png' },
  { atomicNumber: 113, symbol: 'Nh', name: 'Nihonium', category: 'post-transition metal', description: 'Nihonium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/nihonium.png' },
  { atomicNumber: 114, symbol: 'Fl', name: 'Flerovium', category: 'post-transition metal', description: 'Flerovium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/flerovium.png' },
  { atomicNumber: 115, symbol: 'Mc', name: 'Moscovium', category: 'post-transition metal', description: 'Moscovium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/moscovium.png' },
  { atomicNumber: 116, symbol: 'Lv', name: 'Livermorium', category: 'post-transition metal', description: 'Livermorium is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/livermorium.png' },
  { atomicNumber: 117, symbol: 'Ts', name: 'Tennessine', category: 'metalloid', description: 'Tennessine is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/tennessine.png' },
  { atomicNumber: 118, symbol: 'Og', name: 'Oganesson', category: 'noble gas', description: 'Oganesson is used in scientific research and has no significant commercial applications.', image: 'https://example.com/images/oganesson.png' }
},
// Add more elements as needed
};

// Send the element data if it exists, otherwise send a 404 error
if (elementData[elementName]) {
res.json(elementData[elementName]);
} else {
res.status(404).json({ error: 'Element not found' });
}
});;